### ISSUE TITLE
rdf:type and cube.link/observedBy show up as dimensions

### ISSUE THREAD

**Issue by herrstucki** [zazuko/rdf-cube-view-query#35] opened 2021-03-04 10:26 UTC
I don't think those should show up as one of the `cube.dimensions`.

Repro: Run examples/bafu-demo.sh

**Comment by bergos** [comment] 2021-03-10 14:55
fixed in #36

**Closed by bergos** 2021-03-10 14:55 UTC

**Comment by herrstucki** [comment] 2021-03-10 15:13
@bergos Now I'm getting this error, at least for certain cubes:

Run examples/bafu-demo.sh

```
cube: <https://environment.ld.admin.ch/foen/fab_tst_2>
(node:5674) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'termType' of undefined
    at term (/Users/jeremy/Code/zazuko/rdf-cube-view-query/node_modules/@rdfjs/to-ntriples/lib/term.js:8:16)
    at TermSet.has (/Users/jeremy/Code/zazuko/rdf-cube-view-query/node_modules/@rdfjs/term-set/index.js:47:27)
    at /Users/jeremy/Code/zazuko/rdf-cube-view-query/lib/Cube.js:35:40
    at /Users/jeremy/Code/zazuko/rdf-cube-view-query/node_modules/clownface/lib/Clownface.js:178:66
    at Array.filter (<anonymous>)
    at Clownface.filter (/Users/jeremy/Code/zazuko/rdf-cube-view-query/node_modules/clownface/lib/Clownface.js:178:48)
    at Cube.get dimensions [as dimensions] (/Users/jeremy/Code/zazuko/rdf-cube-view-query/lib/Cube.js:35:8)
    at Command.<anonymous> (/Users/jeremy/Code/zazuko/rdf-cube-view-query/bin/rdf-cube-view.js:34:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by bergos** [comment] 2021-03-10 21:06
@herrstucki I also saw it, but it was already there before my changes. It's caused by corrupted data. Cube listing or dimension listing of other cubes should not be affected, that's why I didn't spend time on wrapping it into a more readable error message.

@l00mi any plans for cleaning up the test data?
